name: Dantiao
main: com.valorin.Main
version: EX-31
author: Valorin
api-version: 1.13
softdepend: [HolographicDisplays, PlaceholderAPI, TrHologram, Companions]
commands:
  dantiao:
    description: 查看单挑插件帮助
    usage: /<command>
    aliases: [dt]